<?php

return [
    'workflow_definitions' => [
        'slug' => 'workflows',
        'name' => 'Workflow Definitions',
        'description' => 'Configure approval workflows, routing, and SLA controls.',
        'searchable' => ['name', 'request_type', 'status'],
        'index_columns' => ['name', 'request_type', 'sla_hours', 'status'],
        'fields' => [
            'name' => [
                'label' => 'Workflow Name',
                'type' => 'text',
                'placeholder' => 'Leave Approval Workflow',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'request_type' => [
                'label' => 'Request Type',
                'type' => 'text',
                'placeholder' => 'leave|time_adjustment|onboarding',
                'rules' => ['required', 'string', 'max:100'],
                'index' => true,
            ],
            'steps_json' => [
                'label' => 'Workflow Steps (JSON)',
                'type' => 'textarea',
                'placeholder' => '[{"step":1,"role":"manager"}]',
                'rules' => ['nullable', 'string'],
            ],
            'sla_hours' => [
                'label' => 'SLA (Hours)',
                'type' => 'number',
                'placeholder' => '48',
                'rules' => ['nullable', 'integer', 'min:0'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['ACTIVE', 'INACTIVE'],
                'rules' => ['required', 'in:ACTIVE,INACTIVE'],
                'index' => true,
            ],
        ],
    ],

    'leave_requests' => [
        'slug' => 'leave-requests',
        'name' => 'Leave Requests',
        'description' => 'Manage leave and absence submissions, approvals, and tracking.',
        'searchable' => ['leave_type', 'status', 'approver_name'],
        'index_columns' => ['employee_id', 'leave_type', 'start_date', 'end_date', 'status'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'leave_type' => [
                'label' => 'Leave Type',
                'type' => 'text',
                'placeholder' => 'Annual Leave',
                'rules' => ['required', 'string', 'max:100'],
                'index' => true,
            ],
            'start_date' => [
                'label' => 'Start Date',
                'type' => 'date',
                'rules' => ['required', 'date'],
                'index' => true,
            ],
            'end_date' => [
                'label' => 'End Date',
                'type' => 'date',
                'rules' => ['required', 'date', 'after_or_equal:start_date'],
                'index' => true,
            ],
            'days' => [
                'label' => 'Requested Days',
                'type' => 'number',
                'placeholder' => '3.5',
                'rules' => ['required', 'numeric', 'min:0'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'],
                'rules' => ['required', 'in:PENDING,APPROVED,REJECTED,CANCELLED'],
                'index' => true,
            ],
            'reason' => [
                'label' => 'Reason',
                'type' => 'textarea',
                'placeholder' => 'Optional supporting reason',
                'rules' => ['nullable', 'string'],
            ],
            'approver_name' => [
                'label' => 'Approver',
                'type' => 'text',
                'placeholder' => 'Manager Name',
                'rules' => ['nullable', 'string', 'max:150'],
            ],
        ],
    ],

    'attendance_records' => [
        'slug' => 'attendance-records',
        'name' => 'Attendance Records',
        'description' => 'Capture attendance events, work sessions, and exceptions.',
        'searchable' => ['exception_status', 'notes'],
        'index_columns' => ['employee_id', 'work_date', 'minutes_worked', 'exception_status'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'work_date' => [
                'label' => 'Work Date',
                'type' => 'date',
                'rules' => ['required', 'date'],
                'index' => true,
            ],
            'clock_in' => [
                'label' => 'Clock In',
                'type' => 'datetime-local',
                'rules' => ['nullable', 'date'],
            ],
            'clock_out' => [
                'label' => 'Clock Out',
                'type' => 'datetime-local',
                'rules' => ['nullable', 'date'],
            ],
            'minutes_worked' => [
                'label' => 'Minutes Worked',
                'type' => 'number',
                'placeholder' => '480',
                'rules' => ['nullable', 'integer', 'min:0'],
                'index' => true,
            ],
            'exception_status' => [
                'label' => 'Exception Status',
                'type' => 'select',
                'options' => ['NORMAL', 'MISSING_PUNCH', 'LATE', 'ABNORMAL_OT'],
                'rules' => ['required', 'in:NORMAL,MISSING_PUNCH,LATE,ABNORMAL_OT'],
                'index' => true,
            ],
            'notes' => [
                'label' => 'Notes',
                'type' => 'textarea',
                'placeholder' => 'Exception notes',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'timesheets' => [
        'slug' => 'timesheets',
        'name' => 'Timesheets',
        'description' => 'Manage pay-period timesheets and approvals.',
        'searchable' => ['status', 'approved_by'],
        'index_columns' => ['employee_id', 'period_start', 'period_end', 'total_minutes', 'status'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'period_start' => [
                'label' => 'Period Start',
                'type' => 'date',
                'rules' => ['required', 'date'],
                'index' => true,
            ],
            'period_end' => [
                'label' => 'Period End',
                'type' => 'date',
                'rules' => ['required', 'date', 'after_or_equal:period_start'],
                'index' => true,
            ],
            'total_minutes' => [
                'label' => 'Total Minutes',
                'type' => 'number',
                'placeholder' => '9600',
                'rules' => ['required', 'integer', 'min:0'],
                'index' => true,
            ],
            'overtime_minutes' => [
                'label' => 'Overtime Minutes',
                'type' => 'number',
                'placeholder' => '180',
                'rules' => ['required', 'integer', 'min:0'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'LOCKED'],
                'rules' => ['required', 'in:DRAFT,SUBMITTED,APPROVED,REJECTED,LOCKED'],
                'index' => true,
            ],
            'approved_by' => [
                'label' => 'Approved By',
                'type' => 'text',
                'placeholder' => 'Approver name',
                'rules' => ['nullable', 'string', 'max:150'],
            ],
        ],
    ],

    'payroll_exports' => [
        'slug' => 'payroll-exports',
        'name' => 'Payroll Exports',
        'description' => 'Generate and monitor payroll-ready export batches and reconciliations.',
        'searchable' => ['export_version', 'status', 'file_reference'],
        'index_columns' => ['period_start', 'period_end', 'export_version', 'status'],
        'fields' => [
            'period_start' => [
                'label' => 'Period Start',
                'type' => 'date',
                'rules' => ['required', 'date'],
                'index' => true,
            ],
            'period_end' => [
                'label' => 'Period End',
                'type' => 'date',
                'rules' => ['required', 'date', 'after_or_equal:period_start'],
                'index' => true,
            ],
            'export_version' => [
                'label' => 'Export Version',
                'type' => 'text',
                'placeholder' => 'v1.0',
                'rules' => ['required', 'string', 'max:32'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['PREPARED', 'EXPORTED', 'RECONCILED', 'FAILED'],
                'rules' => ['required', 'in:PREPARED,EXPORTED,RECONCILED,FAILED'],
                'index' => true,
            ],
            'exported_at' => [
                'label' => 'Exported At',
                'type' => 'datetime-local',
                'rules' => ['nullable', 'date'],
            ],
            'file_reference' => [
                'label' => 'File Reference',
                'type' => 'text',
                'placeholder' => 'payroll_exports/2026-03.csv',
                'rules' => ['nullable', 'string', 'max:255'],
            ],
            'notes' => [
                'label' => 'Notes',
                'type' => 'textarea',
                'placeholder' => 'Reconciliation notes',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'job_requisitions' => [
        'slug' => 'job-requisitions',
        'name' => 'Job Requisitions',
        'description' => 'Track recruitment requisitions and hiring demand.',
        'searchable' => ['requisition_code', 'title', 'department', 'status'],
        'index_columns' => ['requisition_code', 'title', 'department', 'status'],
        'fields' => [
            'requisition_code' => [
                'label' => 'Requisition Code',
                'type' => 'text',
                'placeholder' => 'REQ-2026-001',
                'rules' => ['required', 'string', 'max:64'],
                'index' => true,
                'unique' => true,
            ],
            'title' => [
                'label' => 'Title',
                'type' => 'text',
                'placeholder' => 'Senior Nurse',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'department' => [
                'label' => 'Department',
                'type' => 'text',
                'placeholder' => 'Clinical Services',
                'rules' => ['nullable', 'string', 'max:120'],
                'index' => true,
            ],
            'hiring_manager' => [
                'label' => 'Hiring Manager',
                'type' => 'text',
                'placeholder' => 'Manager Name',
                'rules' => ['nullable', 'string', 'max:150'],
            ],
            'openings' => [
                'label' => 'Openings',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['required', 'integer', 'min:1'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['OPEN', 'ON_HOLD', 'CLOSED', 'FILLED'],
                'rules' => ['required', 'in:OPEN,ON_HOLD,CLOSED,FILLED'],
                'index' => true,
            ],
            'target_start_date' => [
                'label' => 'Target Start Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
            ],
        ],
    ],

    'candidate_profiles' => [
        'slug' => 'candidates',
        'name' => 'Candidate Profiles',
        'description' => 'Manage applicant pipeline from application to conversion.',
        'searchable' => ['full_name', 'email', 'stage', 'status'],
        'index_columns' => ['full_name', 'email', 'stage', 'status'],
        'fields' => [
            'requisition_code' => [
                'label' => 'Requisition Code',
                'type' => 'text',
                'placeholder' => 'REQ-2026-001',
                'rules' => ['nullable', 'string', 'max:64'],
            ],
            'full_name' => [
                'label' => 'Candidate Name',
                'type' => 'text',
                'placeholder' => 'Jane Doe',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'email' => [
                'label' => 'Email',
                'type' => 'text',
                'placeholder' => 'candidate@example.com',
                'rules' => ['nullable', 'email', 'max:150'],
                'index' => true,
            ],
            'phone' => [
                'label' => 'Phone',
                'type' => 'text',
                'placeholder' => '+263...',
                'rules' => ['nullable', 'string', 'max:64'],
            ],
            'stage' => [
                'label' => 'Pipeline Stage',
                'type' => 'select',
                'options' => ['APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED'],
                'rules' => ['required', 'in:APPLIED,SCREENING,INTERVIEW,OFFER,HIRED,REJECTED'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['ACTIVE', 'HIRED', 'WITHDRAWN', 'REJECTED'],
                'rules' => ['required', 'in:ACTIVE,HIRED,WITHDRAWN,REJECTED'],
                'index' => true,
            ],
            'notes' => [
                'label' => 'Notes',
                'type' => 'textarea',
                'placeholder' => 'Interview feedback',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'onboarding_tasks' => [
        'slug' => 'onboarding-tasks',
        'name' => 'Onboarding Tasks',
        'description' => 'Coordinate onboarding checklists and completion evidence.',
        'searchable' => ['task_name', 'owner_team', 'status'],
        'index_columns' => ['employee_id', 'task_name', 'owner_team', 'status', 'due_date'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'task_name' => [
                'label' => 'Task Name',
                'type' => 'text',
                'placeholder' => 'Issue access card',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'owner_team' => [
                'label' => 'Owner Team',
                'type' => 'text',
                'placeholder' => 'IT/Facilities/HR',
                'rules' => ['nullable', 'string', 'max:120'],
                'index' => true,
            ],
            'due_date' => [
                'label' => 'Due Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['OPEN', 'IN_PROGRESS', 'DONE', 'OVERDUE'],
                'rules' => ['required', 'in:OPEN,IN_PROGRESS,DONE,OVERDUE'],
                'index' => true,
            ],
            'notes' => [
                'label' => 'Notes',
                'type' => 'textarea',
                'placeholder' => 'Completion details',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'offboarding_tasks' => [
        'slug' => 'offboarding-tasks',
        'name' => 'Offboarding Tasks',
        'description' => 'Track clearance, deprovisioning, and exit checklist tasks.',
        'searchable' => ['task_name', 'owner_team', 'status'],
        'index_columns' => ['employee_id', 'task_name', 'owner_team', 'status', 'due_date'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'task_name' => [
                'label' => 'Task Name',
                'type' => 'text',
                'placeholder' => 'Recover company laptop',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'owner_team' => [
                'label' => 'Owner Team',
                'type' => 'text',
                'placeholder' => 'IT/HR/Finance',
                'rules' => ['nullable', 'string', 'max:120'],
                'index' => true,
            ],
            'due_date' => [
                'label' => 'Due Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['OPEN', 'IN_PROGRESS', 'CLEARED', 'BLOCKED'],
                'rules' => ['required', 'in:OPEN,IN_PROGRESS,CLEARED,BLOCKED'],
                'index' => true,
            ],
            'notes' => [
                'label' => 'Notes',
                'type' => 'textarea',
                'placeholder' => 'Clearance evidence',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'performance_reviews' => [
        'slug' => 'performance-reviews',
        'name' => 'Performance Reviews',
        'description' => 'Manage review cycles, ratings, and calibration notes.',
        'searchable' => ['cycle_name', 'reviewer_name', 'status'],
        'index_columns' => ['employee_id', 'cycle_name', 'review_date', 'rating', 'status'],
        'fields' => [
            'employee_id' => [
                'label' => 'Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['nullable', 'integer', 'min:1'],
                'index' => true,
            ],
            'cycle_name' => [
                'label' => 'Review Cycle',
                'type' => 'text',
                'placeholder' => '2026 Mid-Year',
                'rules' => ['required', 'string', 'max:120'],
                'index' => true,
            ],
            'reviewer_name' => [
                'label' => 'Reviewer',
                'type' => 'text',
                'placeholder' => 'Reviewer name',
                'rules' => ['nullable', 'string', 'max:150'],
            ],
            'rating' => [
                'label' => 'Rating',
                'type' => 'number',
                'placeholder' => '4.5',
                'rules' => ['nullable', 'numeric', 'between:0,5'],
                'index' => true,
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['PLANNED', 'IN_REVIEW', 'COMPLETED'],
                'rules' => ['required', 'in:PLANNED,IN_REVIEW,COMPLETED'],
                'index' => true,
            ],
            'review_date' => [
                'label' => 'Review Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
                'index' => true,
            ],
            'comments' => [
                'label' => 'Comments',
                'type' => 'textarea',
                'placeholder' => 'Manager comments',
                'rules' => ['nullable', 'string'],
            ],
        ],
    ],

    'learning_courses' => [
        'slug' => 'learning-courses',
        'name' => 'Learning Courses',
        'description' => 'Maintain training catalog, compliance courses, and status.',
        'searchable' => ['course_code', 'title', 'category', 'status'],
        'index_columns' => ['course_code', 'title', 'category', 'status'],
        'fields' => [
            'course_code' => [
                'label' => 'Course Code',
                'type' => 'text',
                'placeholder' => 'LMS-001',
                'rules' => ['required', 'string', 'max:64'],
                'index' => true,
                'unique' => true,
            ],
            'title' => [
                'label' => 'Course Title',
                'type' => 'text',
                'placeholder' => 'Workplace Safety Basics',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'category' => [
                'label' => 'Category',
                'type' => 'text',
                'placeholder' => 'Compliance',
                'rules' => ['nullable', 'string', 'max:120'],
                'index' => true,
            ],
            'duration_hours' => [
                'label' => 'Duration (Hours)',
                'type' => 'number',
                'placeholder' => '2.5',
                'rules' => ['nullable', 'numeric', 'min:0'],
            ],
            'compliance_required' => [
                'label' => 'Compliance Required',
                'type' => 'checkbox',
                'rules' => ['boolean'],
            ],
            'expires_after_days' => [
                'label' => 'Expires After (Days)',
                'type' => 'number',
                'placeholder' => '365',
                'rules' => ['nullable', 'integer', 'min:0'],
            ],
            'status' => [
                'label' => 'Status',
                'type' => 'select',
                'options' => ['ACTIVE', 'INACTIVE', 'ARCHIVED'],
                'rules' => ['required', 'in:ACTIVE,INACTIVE,ARCHIVED'],
                'index' => true,
            ],
        ],
    ],

    'document_types' => [
        'slug' => 'document-types',
        'name' => 'Document Types',
        'description' => 'Manage document category master data and retention policies.',
        'searchable' => ['code', 'name', 'sensitivity_level'],
        'index_columns' => ['code', 'name', 'sensitivity_level'],
        'fields' => [
            'code' => [
                'label' => 'Code',
                'type' => 'text',
                'placeholder' => 'CONTRACT',
                'rules' => ['required', 'string', 'max:64'],
                'index' => true,
                'unique' => true,
            ],
            'name' => [
                'label' => 'Name',
                'type' => 'text',
                'placeholder' => 'Employment Contract',
                'rules' => ['required', 'string', 'max:150'],
                'index' => true,
            ],
            'retention_policy' => [
                'label' => 'Retention Policy',
                'type' => 'text',
                'placeholder' => '7 years after termination',
                'rules' => ['nullable', 'string', 'max:255'],
            ],
            'sensitivity_level' => [
                'label' => 'Sensitivity Level',
                'type' => 'select',
                'options' => ['NORMAL', 'CONFIDENTIAL', 'HIGHLY_CONFIDENTIAL'],
                'rules' => ['required', 'in:NORMAL,CONFIDENTIAL,HIGHLY_CONFIDENTIAL'],
                'index' => true,
            ],
        ],
    ],

    'documents' => [
        'slug' => 'documents',
        'name' => 'Documents',
        'description' => 'Manage employee documents, validity windows, and access policies.',
        'searchable' => ['title', 'file_uri', 'access_policy'],
        'index_columns' => ['owner_employee_id', 'document_type_id', 'title', 'expiry_date'],
        'fields' => [
            'owner_employee_id' => [
                'label' => 'Owner Employee ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['required', 'integer', 'min:1'],
                'index' => true,
            ],
            'document_type_id' => [
                'label' => 'Document Type ID',
                'type' => 'number',
                'placeholder' => '1',
                'rules' => ['required', 'integer', 'min:1'],
                'index' => true,
            ],
            'title' => [
                'label' => 'Title',
                'type' => 'text',
                'placeholder' => 'Employment Contract - 2026',
                'rules' => ['nullable', 'string', 'max:255'],
                'index' => true,
            ],
            'file_uri' => [
                'label' => 'File URI',
                'type' => 'text',
                'placeholder' => 'documents/contracts/emp001.pdf',
                'rules' => ['required', 'string', 'max:255'],
            ],
            'issue_date' => [
                'label' => 'Issue Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
            ],
            'expiry_date' => [
                'label' => 'Expiry Date',
                'type' => 'date',
                'rules' => ['nullable', 'date'],
                'index' => true,
            ],
            'metadata_json' => [
                'label' => 'Metadata (JSON)',
                'type' => 'textarea',
                'placeholder' => '{"issuer":"HR"}',
                'rules' => ['nullable', 'string'],
            ],
            'access_policy' => [
                'label' => 'Access Policy',
                'type' => 'select',
                'options' => ['OWNER_AND_HR', 'OWNER_MANAGER_HR', 'HR_ONLY'],
                'rules' => ['required', 'in:OWNER_AND_HR,OWNER_MANAGER_HR,HR_ONLY'],
                'index' => true,
            ],
        ],
    ],
];
