<?php

return [
    'default_currency' => env('PAYROLL_DEFAULT_CURRENCY', 'USD'),

    'currencies' => [
        ['code' => 'USD', 'label' => 'US Dollar'],
        ['code' => 'ZIG', 'label' => 'ZiG'],
    ],

    'settlement_allocation_methods' => [
        'FIXED_AMOUNT',
        'PERCENTAGE',
        'REMAINDER',
    ],

    'standard_monthly_hours' => (float) env('PAYROLL_STANDARD_MONTHLY_HOURS', 173.33),

    'frequencies' => [
        'MONTHLY',
        'FORTNIGHTLY',
        'BI_WEEKLY',
        'WEEKLY',
    ],

    'period_statuses' => [
        'DRAFT',
        'PROCESSED',
        'APPROVED',
        'CLOSED',
    ],

    'run_statuses' => [
        'PROCESSED',
        'APPROVED',
        'CLOSED',
        'SUPERSEDED',
    ],

    'default_pay_codes' => [
        [
            'code' => 'BASIC',
            'description' => 'Basic salary',
            'category' => 'SALARY',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => true,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 10,
        ],
        [
            'code' => 'HOU',
            'description' => 'Housing allowance',
            'category' => 'ALLOWANCE',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => true,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 20,
        ],
        [
            'code' => 'TRANS',
            'description' => 'Transport allowance',
            'category' => 'ALLOWANCE',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => true,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 30,
        ],
        [
            'code' => 'OT',
            'description' => 'Overtime',
            'category' => 'OVERTIME',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => false,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 40,
        ],
        [
            'code' => 'BONUS',
            'description' => 'Bonus',
            'category' => 'BONUS',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => false,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 50,
        ],
        [
            'code' => 'ACT',
            'description' => 'Acting allowance',
            'category' => 'ALLOWANCE',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => false,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 60,
        ],
        [
            'code' => 'CILL',
            'description' => 'Cellphone allowance',
            'category' => 'ALLOWANCE',
            'type' => 'EARNING',
            'taxable' => true,
            'recurring' => false,
            'affects_gross' => true,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 70,
        ],
        [
            'code' => 'PENS',
            'description' => 'Pension',
            'category' => 'STATUTORY',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => true,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 80,
        ],
        [
            'code' => 'NSSA',
            'description' => 'NSSA contribution',
            'category' => 'STATUTORY',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => true,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 90,
        ],
        [
            'code' => 'NEC',
            'description' => 'NEC contribution',
            'category' => 'STATUTORY',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 100,
        ],
        [
            'code' => 'UNION',
            'description' => 'Union deductions',
            'category' => 'VOLUNTARY',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 110,
        ],
        [
            'code' => 'LOAN',
            'description' => 'Loan repayment',
            'category' => 'VOLUNTARY',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => false,
            'sort_order' => 120,
        ],
        [
            'code' => 'PAYE',
            'description' => 'PAYE tax',
            'category' => 'TAX',
            'type' => 'DEDUCTION',
            'taxable' => false,
            'recurring' => true,
            'affects_gross' => false,
            'affects_net' => true,
            'is_pre_tax' => false,
            'active' => true,
            'system_generated' => true,
            'sort_order' => 130,
        ],
    ],

    'statutory' => [
        'nssa' => [
            'cap' => 700.00,
            'default_percent' => 4.5,
        ],
        'nec' => [
            'default_percent' => 1.0,
        ],
        'pension' => [
            'default_percent' => 5.0,
        ],
        'union' => [
            'default_percent' => 0.0,
        ],
    ],

    'tax' => [
        'bands' => [
            ['up_to' => 1000.00, 'rate' => 0.00, 'base' => 0.00],
            ['up_to' => 3000.00, 'rate' => 0.20, 'base' => 0.00],
            ['up_to' => 6000.00, 'rate' => 0.30, 'base' => 400.00],
            ['up_to' => null, 'rate' => 0.40, 'base' => 1300.00],
        ],
    ],
];
