<?php

return [
    'groups' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'description' => 'Executive summaries, alerts, and cross-module insights.',
            'permissions' => [
                ['name' => 'dashboard.view', 'label' => 'View dashboard', 'description' => 'Access the HRMS dashboard and summary widgets.'],
            ],
        ],
        [
            'key' => 'employees',
            'label' => 'Employees',
            'description' => 'Employee records, lifecycle updates, and bulk imports.',
            'permissions' => [
                ['name' => 'employees.view', 'label' => 'View employees', 'description' => 'Open employee listings and profile details.'],
                ['name' => 'employees.create', 'label' => 'Create employees', 'description' => 'Create new employee records and linked accounts.'],
                ['name' => 'employees.update', 'label' => 'Update employees', 'description' => 'Edit employee profiles and linked data.'],
                ['name' => 'employees.delete', 'label' => 'Delete employees', 'description' => 'Delete employee records when allowed by business rules.'],
                ['name' => 'employees.bulk_upload', 'label' => 'Bulk upload employees', 'description' => 'Import employee records from templates and bulk files.'],
            ],
        ],
        [
            'key' => 'org_units',
            'label' => 'Organisation Units',
            'description' => 'Companies, SBUs, departments, and teams.',
            'permissions' => [
                ['name' => 'org_units.view', 'label' => 'View org units', 'description' => 'Browse the organisation structure.'],
                ['name' => 'org_units.create', 'label' => 'Create org units', 'description' => 'Add organisational units.'],
                ['name' => 'org_units.update', 'label' => 'Update org units', 'description' => 'Edit organisational structures and metadata.'],
                ['name' => 'org_units.delete', 'label' => 'Delete org units', 'description' => 'Remove organisation units when safe.'],
                ['name' => 'org_units.bulk_upload', 'label' => 'Bulk upload org units', 'description' => 'Import organisation structures from templates.'],
            ],
        ],
        [
            'key' => 'locations',
            'label' => 'Locations',
            'description' => 'Physical work locations and operational sites.',
            'permissions' => [
                ['name' => 'locations.view', 'label' => 'View locations', 'description' => 'Browse and inspect locations.'],
                ['name' => 'locations.create', 'label' => 'Create locations', 'description' => 'Add work locations and branches.'],
                ['name' => 'locations.update', 'label' => 'Update locations', 'description' => 'Edit location details.'],
                ['name' => 'locations.delete', 'label' => 'Delete locations', 'description' => 'Delete locations when safe.'],
                ['name' => 'locations.bulk_upload', 'label' => 'Bulk upload locations', 'description' => 'Import location data from templates.'],
            ],
        ],
        [
            'key' => 'positions',
            'label' => 'Positions',
            'description' => 'Job positions and staffing templates.',
            'permissions' => [
                ['name' => 'positions.view', 'label' => 'View positions', 'description' => 'Browse positions and assignments.'],
                ['name' => 'positions.create', 'label' => 'Create positions', 'description' => 'Add new positions.'],
                ['name' => 'positions.update', 'label' => 'Update positions', 'description' => 'Edit positions and attributes.'],
                ['name' => 'positions.delete', 'label' => 'Delete positions', 'description' => 'Delete positions when safe.'],
                ['name' => 'positions.bulk_upload', 'label' => 'Bulk upload positions', 'description' => 'Import positions from templates.'],
            ],
        ],
        [
            'key' => 'users',
            'label' => 'Users',
            'description' => 'Application users, access, and account maintenance.',
            'permissions' => [
                ['name' => 'users.view', 'label' => 'View users', 'description' => 'Browse user accounts and account details.'],
                ['name' => 'users.create', 'label' => 'Create users', 'description' => 'Create new user accounts.'],
                ['name' => 'users.update', 'label' => 'Update users', 'description' => 'Update user profiles and credentials.'],
                ['name' => 'users.delete', 'label' => 'Delete users', 'description' => 'Delete user accounts when safe.'],
                ['name' => 'users.assign_roles', 'label' => 'Assign roles to users', 'description' => 'Assign and update role memberships on users.'],
            ],
        ],
        [
            'key' => 'roles',
            'label' => 'Roles',
            'description' => 'Role definitions and access tiers.',
            'permissions' => [
                ['name' => 'roles.view', 'label' => 'View roles', 'description' => 'Browse roles and role details.'],
                ['name' => 'roles.create', 'label' => 'Create roles', 'description' => 'Create new roles dynamically.'],
                ['name' => 'roles.update', 'label' => 'Update roles', 'description' => 'Edit role details and assignments.'],
                ['name' => 'roles.delete', 'label' => 'Delete roles', 'description' => 'Delete removable roles.'],
            ],
        ],
        [
            'key' => 'permissions',
            'label' => 'Permissions',
            'description' => 'Permission catalogues and role assignment matrices.',
            'permissions' => [
                ['name' => 'permissions.view', 'label' => 'View permissions', 'description' => 'Browse permission matrices and groupings.'],
                ['name' => 'permissions.assign', 'label' => 'Assign permissions', 'description' => 'Assign and update permissions on roles.'],
            ],
        ],
        [
            'key' => 'audit',
            'label' => 'Audit Trail',
            'description' => 'Application-wide audit logs, investigations, and compliance exports.',
            'permissions' => [
                ['name' => 'audit.view', 'label' => 'View audit trail', 'description' => 'Browse audit logs, investigations, and audit dashboards.'],
                ['name' => 'audit.export', 'label' => 'Export audit trail', 'description' => 'Export audit log data for compliance, security, and investigations.'],
                ['name' => 'audit.manage', 'label' => 'Manage audit trail', 'description' => 'Perform elevated audit administration actions such as retention or operational management.'],
            ],
        ],
        [
            'key' => 'organizations',
            'label' => 'Organizations',
            'description' => 'Tenant organizations, memberships, switching, and organization administration.',
            'permissions' => [
                ['name' => 'organizations.view', 'label' => 'View organizations', 'description' => 'Browse organizations and organization details.'],
                ['name' => 'organizations.create', 'label' => 'Create organizations', 'description' => 'Create new tenant organizations.'],
                ['name' => 'organizations.update', 'label' => 'Update organizations', 'description' => 'Update organization settings, branding, and status.'],
                ['name' => 'organizations.delete', 'label' => 'Delete organizations', 'description' => 'Archive or delete organizations when safe.'],
                ['name' => 'organizations.manage_members', 'label' => 'Manage organization members', 'description' => 'Assign users, activate memberships, and manage organization-level roles.'],
                ['name' => 'organizations.switch', 'label' => 'Switch organizations', 'description' => 'Switch the active organization context when the user belongs to multiple organizations.'],
            ],
        ],
        [
            'key' => 'workflows',
            'label' => 'Workflows',
            'description' => 'Workflow definitions and module automation.',
            'permissions' => [
                ['name' => 'workflows.view', 'label' => 'View workflows', 'description' => 'Browse workflow definitions.'],
                ['name' => 'workflows.create', 'label' => 'Create workflows', 'description' => 'Create workflow definitions.'],
                ['name' => 'workflows.update', 'label' => 'Update workflows', 'description' => 'Edit workflow definitions.'],
                ['name' => 'workflows.delete', 'label' => 'Delete workflows', 'description' => 'Delete workflow definitions.'],
            ],
        ],
        [
            'key' => 'leave',
            'label' => 'Leave',
            'description' => 'Leave request creation, review, and approvals.',
            'permissions' => [
                ['name' => 'leave.view', 'label' => 'View leave requests', 'description' => 'Browse leave requests and related records.'],
                ['name' => 'leave.create', 'label' => 'Create leave requests', 'description' => 'Create leave requests and related notes.'],
                ['name' => 'leave.update', 'label' => 'Update leave requests', 'description' => 'Edit leave requests.'],
                ['name' => 'leave.delete', 'label' => 'Delete leave requests', 'description' => 'Delete leave requests where allowed.'],
                ['name' => 'leave.approve', 'label' => 'Approve leave requests', 'description' => 'Approve, deny, or request changes on leave requests.'],
                ['name' => 'leave.manage', 'label' => 'Manage leave', 'description' => 'Perform administrative leave management actions.'],
            ],
        ],
        [
            'key' => 'attendance',
            'label' => 'Attendance',
            'description' => 'Attendance records and attendance administration.',
            'permissions' => [
                ['name' => 'attendance.view', 'label' => 'View attendance', 'description' => 'Browse attendance registers and record detail.'],
                ['name' => 'attendance.create', 'label' => 'Create attendance records', 'description' => 'Create attendance records.'],
                ['name' => 'attendance.update', 'label' => 'Update attendance records', 'description' => 'Edit attendance records.'],
                ['name' => 'attendance.delete', 'label' => 'Delete attendance records', 'description' => 'Delete attendance records.'],
                ['name' => 'attendance.manage', 'label' => 'Manage attendance', 'description' => 'Perform attendance administration actions.'],
            ],
        ],
        [
            'key' => 'timesheets',
            'label' => 'Timesheets',
            'description' => 'Timesheet entry, approvals, and bulk processing.',
            'permissions' => [
                ['name' => 'timesheets.view', 'label' => 'View timesheets', 'description' => 'Browse timesheets and related details.'],
                ['name' => 'timesheets.create', 'label' => 'Create timesheets', 'description' => 'Create timesheets.'],
                ['name' => 'timesheets.update', 'label' => 'Update timesheets', 'description' => 'Edit timesheets.'],
                ['name' => 'timesheets.delete', 'label' => 'Delete timesheets', 'description' => 'Delete timesheets.'],
                ['name' => 'timesheets.approve', 'label' => 'Approve timesheets', 'description' => 'Approve or reject timesheets.'],
                ['name' => 'timesheets.bulk_upload', 'label' => 'Bulk upload timesheets', 'description' => 'Process timesheet bulk uploads and imports.'],
            ],
        ],
        [
            'key' => 'payroll',
            'label' => 'Payroll',
            'description' => 'Payroll periods, profiles, calculations, approvals, payslips, and payroll outputs.',
            'permissions' => [
                ['name' => 'payroll.view', 'label' => 'View payroll', 'description' => 'Browse payroll dashboards, periods, and payroll results.'],
                ['name' => 'payroll.manage', 'label' => 'Manage payroll setup', 'description' => 'Create and maintain payroll periods and operational payroll settings.'],
                ['name' => 'payroll.process', 'label' => 'Process payroll', 'description' => 'Run payroll calculations and create payroll runs.'],
                ['name' => 'payroll.approve', 'label' => 'Approve payroll', 'description' => 'Approve processed payroll runs before closure.'],
                ['name' => 'payroll.close', 'label' => 'Close payroll', 'description' => 'Close payroll periods and control reopening.'],
                ['name' => 'payroll.export', 'label' => 'Export payroll outputs', 'description' => 'Export payroll registers, payslips, bank summaries, and journals.'],
                ['name' => 'payroll.profile.manage', 'label' => 'Manage payroll profiles', 'description' => 'Create and update employee payroll profiles and recurring pay items.'],
                ['name' => 'payroll.paycodes.manage', 'label' => 'Manage pay codes', 'description' => 'Create and update earnings and deduction pay codes.'],
                ['name' => 'payroll.inputs.manage', 'label' => 'Manage payroll inputs', 'description' => 'Capture and import period payroll inputs.'],
                ['name' => 'payroll.reports.view', 'label' => 'View payroll reports', 'description' => 'Open payroll report and export screens.'],
                ['name' => 'payroll.create', 'label' => 'Create payroll exports', 'description' => 'Create legacy payroll export records.'],
                ['name' => 'payroll.update', 'label' => 'Update payroll exports', 'description' => 'Edit legacy payroll export records and metadata.'],
                ['name' => 'payroll.delete', 'label' => 'Delete payroll exports', 'description' => 'Delete legacy payroll export records.'],
                ['name' => 'payroll.run', 'label' => 'Run payroll automation', 'description' => 'Run legacy payroll export automation and retries.'],
            ],
        ],
        [
            'key' => 'payslips',
            'label' => 'Payslips',
            'description' => 'Payslip viewing, downloads, email distribution, and SMS summaries.',
            'permissions' => [
                ['name' => 'payslips.view', 'label' => 'View payslips', 'description' => 'Browse payslip listings and payslip detail pages.'],
                ['name' => 'payslips.download', 'label' => 'Download payslips', 'description' => 'Download individual payslip PDFs.'],
                ['name' => 'payslips.email', 'label' => 'Email payslips', 'description' => 'Send an individual payslip by email with PDF attachment.'],
                ['name' => 'payslips.sms', 'label' => 'Send payslip SMS', 'description' => 'Send an individual payslip summary by SMS.'],
                ['name' => 'payslips.bulk_email', 'label' => 'Bulk email payslips', 'description' => 'Send payslip PDFs in bulk for selected employees or periods.'],
                ['name' => 'payslips.bulk_sms', 'label' => 'Bulk send payslip SMS', 'description' => 'Send payslip summary SMS messages in bulk for selected employees or periods.'],
            ],
        ],
        [
            'key' => 'requisitions',
            'label' => 'Requisitions',
            'description' => 'Job requisitions and openings.',
            'permissions' => [
                ['name' => 'requisitions.view', 'label' => 'View requisitions', 'description' => 'Browse job requisitions.'],
                ['name' => 'requisitions.create', 'label' => 'Create requisitions', 'description' => 'Create job requisitions.'],
                ['name' => 'requisitions.update', 'label' => 'Update requisitions', 'description' => 'Edit job requisitions.'],
                ['name' => 'requisitions.delete', 'label' => 'Delete requisitions', 'description' => 'Delete job requisitions.'],
            ],
        ],
        [
            'key' => 'candidates',
            'label' => 'Candidates',
            'description' => 'Candidate profiles and recruitment progress.',
            'permissions' => [
                ['name' => 'candidates.view', 'label' => 'View candidates', 'description' => 'Browse candidate profiles.'],
                ['name' => 'candidates.create', 'label' => 'Create candidates', 'description' => 'Create candidate profiles.'],
                ['name' => 'candidates.update', 'label' => 'Update candidates', 'description' => 'Edit candidate profiles.'],
                ['name' => 'candidates.delete', 'label' => 'Delete candidates', 'description' => 'Delete candidate profiles.'],
            ],
        ],
        [
            'key' => 'onboarding',
            'label' => 'Onboarding',
            'description' => 'Onboarding tasks and completion workflows.',
            'permissions' => [
                ['name' => 'onboarding.view', 'label' => 'View onboarding tasks', 'description' => 'Browse onboarding tasks.'],
                ['name' => 'onboarding.create', 'label' => 'Create onboarding tasks', 'description' => 'Create onboarding tasks.'],
                ['name' => 'onboarding.update', 'label' => 'Update onboarding tasks', 'description' => 'Edit onboarding tasks.'],
                ['name' => 'onboarding.delete', 'label' => 'Delete onboarding tasks', 'description' => 'Delete onboarding tasks.'],
                ['name' => 'onboarding.manage', 'label' => 'Manage onboarding', 'description' => 'Perform administrative onboarding actions.'],
            ],
        ],
        [
            'key' => 'offboarding',
            'label' => 'Offboarding',
            'description' => 'Offboarding tasks and employee exits.',
            'permissions' => [
                ['name' => 'offboarding.view', 'label' => 'View offboarding tasks', 'description' => 'Browse offboarding tasks.'],
                ['name' => 'offboarding.create', 'label' => 'Create offboarding tasks', 'description' => 'Create offboarding tasks.'],
                ['name' => 'offboarding.update', 'label' => 'Update offboarding tasks', 'description' => 'Edit offboarding tasks.'],
                ['name' => 'offboarding.delete', 'label' => 'Delete offboarding tasks', 'description' => 'Delete offboarding tasks.'],
                ['name' => 'offboarding.manage', 'label' => 'Manage offboarding', 'description' => 'Perform administrative offboarding actions.'],
            ],
        ],
        [
            'key' => 'performance',
            'label' => 'Performance',
            'description' => 'Performance reviews and review cycles.',
            'permissions' => [
                ['name' => 'performance.view', 'label' => 'View performance reviews', 'description' => 'Browse performance reviews.'],
                ['name' => 'performance.create', 'label' => 'Create performance reviews', 'description' => 'Create performance reviews.'],
                ['name' => 'performance.update', 'label' => 'Update performance reviews', 'description' => 'Edit performance reviews.'],
                ['name' => 'performance.delete', 'label' => 'Delete performance reviews', 'description' => 'Delete performance reviews.'],
                ['name' => 'performance.manage', 'label' => 'Manage performance', 'description' => 'Perform administrative review-cycle actions.'],
            ],
        ],
        [
            'key' => 'learning',
            'label' => 'Learning',
            'description' => 'Learning courses and compliance training.',
            'permissions' => [
                ['name' => 'learning.view', 'label' => 'View learning courses', 'description' => 'Browse learning courses.'],
                ['name' => 'learning.create', 'label' => 'Create learning courses', 'description' => 'Create learning courses.'],
                ['name' => 'learning.update', 'label' => 'Update learning courses', 'description' => 'Edit learning courses.'],
                ['name' => 'learning.delete', 'label' => 'Delete learning courses', 'description' => 'Delete learning courses.'],
                ['name' => 'learning.manage', 'label' => 'Manage learning', 'description' => 'Perform administrative learning actions.'],
            ],
        ],
        [
            'key' => 'documents',
            'label' => 'Documents',
            'description' => 'Document libraries, document types, and document recovery.',
            'permissions' => [
                ['name' => 'documents.view', 'label' => 'View documents', 'description' => 'Browse documents and document detail.'],
                ['name' => 'documents.create', 'label' => 'Create documents', 'description' => 'Create and upload documents.'],
                ['name' => 'documents.update', 'label' => 'Update documents', 'description' => 'Edit document metadata.'],
                ['name' => 'documents.delete', 'label' => 'Delete documents', 'description' => 'Delete or purge documents.'],
                ['name' => 'documents.restore', 'label' => 'Restore documents', 'description' => 'Restore soft-deleted documents.'],
                ['name' => 'documents.manage', 'label' => 'Manage documents', 'description' => 'Perform document administration actions.'],
                ['name' => 'document_types.view', 'label' => 'View document types', 'description' => 'Browse document types.'],
                ['name' => 'document_types.create', 'label' => 'Create document types', 'description' => 'Create document types.'],
                ['name' => 'document_types.update', 'label' => 'Update document types', 'description' => 'Edit document types.'],
                ['name' => 'document_types.delete', 'label' => 'Delete document types', 'description' => 'Delete document types.'],
            ],
        ],
        [
            'key' => 'reports',
            'label' => 'Reports',
            'description' => 'Operational reports and report exports.',
            'permissions' => [
                ['name' => 'reports.view', 'label' => 'View reports', 'description' => 'Browse the report center and report pages.'],
                ['name' => 'reports.export', 'label' => 'Export reports', 'description' => 'Export or download report output.'],
            ],
        ],
    ],
    'default_role_permissions' => [
        'SYS_ADMIN' => ['*'],
        'HR_ADMIN' => ['dashboard.view','employees.*','org_units.*','locations.*','positions.*','users.view','users.create','users.update','users.assign_roles','roles.*','permissions.*','audit.view','audit.export','organizations.view','organizations.update','organizations.manage_members','organizations.switch','workflows.*','leave.*','attendance.view','attendance.manage','timesheets.view','timesheets.approve','payroll.view','payroll.manage','payroll.process','payroll.approve','payroll.close','payroll.export','payroll.profile.manage','payroll.paycodes.manage','payroll.inputs.manage','payroll.reports.view','payslips.*','requisitions.*','candidates.*','onboarding.*','offboarding.*','performance.*','learning.*','documents.*','document_types.*','reports.*'],
        'PAYROLL' => ['dashboard.view','employees.view','users.view','timesheets.view','timesheets.approve','attendance.view','payroll.*','payslips.*','documents.view','reports.*'],
        'MANAGER' => ['dashboard.view','employees.view','leave.view','leave.create','leave.approve','attendance.view','attendance.manage','timesheets.view','timesheets.approve','requisitions.view','candidates.view','onboarding.view','offboarding.view','performance.view','performance.manage','learning.view','documents.view','reports.view'],
        'AUTHORISER' => ['dashboard.view','leave.view','leave.approve','timesheets.view','timesheets.approve','payroll.view','payroll.approve','payroll.close','payroll.reports.view','payslips.view','payslips.download','documents.view','reports.view'],
        'EMPLOYEE' => ['dashboard.view','employees.view','leave.view','leave.create','attendance.view','timesheets.view','timesheets.create','documents.view','learning.view','performance.view'],
        'AUDITOR' => ['dashboard.view','audit.view','audit.export','employees.view','users.view','roles.view','permissions.view','organizations.view','workflows.view','leave.view','attendance.view','timesheets.view','payroll.view','payroll.reports.view','payslips.view','payslips.download','requisitions.view','candidates.view','onboarding.view','offboarding.view','performance.view','learning.view','documents.view','document_types.view','reports.*'],
    ],
    'protected_role_codes' => ['SYS_ADMIN','HR_ADMIN','PAYROLL','MANAGER','AUTHORISER','EMPLOYEE','AUDITOR'],
];
