import {
    Activity,
    AlertTriangle,
    BadgeCheck,
    BookOpen,
    Briefcase,
    Building2,
    CalendarDays,
    CalendarPlus,
    Clock3,
    Database,
    Download,
    FileBarChart,
    FileText,
    Heart,
    History,
    LayoutGrid,
    Mail,
    Play,
    Rocket,
    Settings,
    Shield,
    Target,
    User,
    UserPlus,
    Users,
    Wallet,
    type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
    activity: Activity,
    'alert-triangle': AlertTriangle,
    'badge-check': BadgeCheck,
    'book-open': BookOpen,
    briefcase: Briefcase,
    'building-2': Building2,
    'calendar-days': CalendarDays,
    'calendar-plus': CalendarPlus,
    'clock-3': Clock3,
    database: Database,
    download: Download,
    'file-bar-chart': FileBarChart,
    'file-text': FileText,
    heart: Heart,
    history: History,
    'layout-grid': LayoutGrid,
    mail: Mail,
    play: Play,
    rocket: Rocket,
    settings: Settings,
    shield: Shield,
    target: Target,
    user: User,
    'user-plus': UserPlus,
    users: Users,
    wallet: Wallet,
    employees: Users,
    organizations: Building2,
    users_with_access: Shield,
    pending_approvals: Clock3,
    open_hiring: Briefcase,
    documents: FileText,
    pending_leave: CalendarDays,
    onboarding_risk: AlertTriangle,
    open_requisitions: Briefcase,
    reviews_in_flight: Target,
    benefit_enrollments: Heart,
    payroll_periods: Wallet,
    payroll_approval: BadgeCheck,
    failed_exports: Download,
    pending_deliveries: Mail,
    delivery_failures: AlertTriangle,
    direct_reports: Users,
    team_leave: CalendarDays,
    team_timesheets: Clock3,
    review_queue: Target,
    improvement_plans: Target,
    upcoming_absence: CalendarDays,
    payroll_close: Wallet,
    export_failures: Download,
    payslips: Mail,
    my_leave: CalendarDays,
    benefits: Heart,
    scorecards: Target,
    assets: LayoutGrid,
    audit_events: History,
    roles: Shield,
    reviews: Target,
};

export function iconFor(name?: string): LucideIcon {
    if (!name) {
        return LayoutGrid;
    }

    return iconMap[name] ?? LayoutGrid;
}
